# Generated by Django 5.0.4 on 2026-08-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fda',
            table='FDA',
        ),
    ]
